### ISSUE TITLE
UnboundLocalError: local variable 'rpath' referenced before assignment

### ISSUE THREAD

**Issue by zopyx** [collective/transmogrify.ploneremote#3]
NFO:titleguess(pathsorter):adding folder wirtschaft/verkehr_und_infrastruktur/images
INFO:titleguess(pathsorter):adding folder wirtschaft/wirtschaftliche_beteiligungen
INFO:titleguess(pathsorter):adding folder wirtschaft/wirtschaftliche_beteiligungen/documents
INFO:titleguess(pathsorter):adding folder wirtschaft/wirtschaftsfoerderung
INFO:titleguess(pathsorter):adding folder wirtschaft/wirtschaftsfoerderung/images
Traceback (most recent call last):
  File "bin/funnelweb", line 115, in <module>
    funnelweb.runner.runner({'ploneupload': {'target': 'http://admin:123@localhost:13080/Plone'}, 'crawler': {'url': 'file:///home/ajung/www.dahme-spreewald.de'}})
  File "/home/ajung/.buildout/eggs/funnelweb-1.0b4-py2.6.egg/funnelweb/runner/**init**.py", line 108, in runner
    transmogrifier(u'transmogrify.config.funnelweb', **overrides)
  File "/home/ajung/.buildout/eggs/collective.transmogrifier-1.2-py2.6.egg/collective/transmogrifier/transmogrifier.py", line 62, in **call**
    for item in pipeline:
  File "/home/ajung/.buildout/eggs/transmogrify.webcrawler-1.0b4-py2.6.egg/transmogrify/webcrawler/staticcreator.py", line 34, in **iter**
    for item in self.previous:
  File "/home/ajung/.buildout/eggs/transmogrify.ploneremote-1.0b2-py2.6.egg/transmogrify/ploneremote/remoteprune.py", line 88, in **iter**
    for item in self.previous:  
  File "/home/ajung/.buildout/eggs/transmogrify.ploneremote-1.0b2-py2.6.egg/transmogrify/ploneremote/remoteredirector.py", line 25, in **iter**
    for item in self.previous:
  File "/home/ajung/.buildout/eggs/transmogrify.ploneremote-1.0b2-py2.6.egg/transmogrify/ploneremote/remoteworkflowupdater.py", line 40, in **iter**
    for item in self.previous:
  File "/home/ajung/.buildout/eggs/collective.transmogrifier-1.2-py2.6.egg/collective/transmogrifier/sections/inserter.py", line 19, in **iter**
    for item in self.previous:
  File "/home/ajung/.buildout/eggs/transmogrify.ploneremote-1.0b2-py2.6.egg/transmogrify/ploneremote/remotenavigationexcluder.py", line 34, in **iter**
    for item in self.previous:
  File "/home/ajung/.buildout/eggs/transmogrify.ploneremote-1.0b2-py2.6.egg/transmogrify/ploneremote/remoteschemaupdater.py", line 33, in **iter**
    for item in self.previous:
  File "/home/ajung/.buildout/eggs/transmogrify.ploneremote-1.0b2-py2.6.egg/transmogrify/ploneremote/remoteconstructor.py", line 72, in **iter**
    self.logger.warning("Failuire while creating '%s' of type '%s'"% (rpath, type_) )
UnboundLocalError: local variable 'rpath' referenced before assignment

**Comment by djay** [comment]
this has previously been fixed in trunk but no release yet. I'll put in place the memory fix and then release the changes to pypi.

**Comment by djay** [comment]
now been released
